name: monitor-release
on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch: {}
jobs:
  monitor-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: |
          prefix="v$(date -u +'%Y.%m.%d')"
          count=$(gh api "repos/$REPOSITORY/git/matching-refs/tags/$prefix" -q 'length' || echo 0)
          if [ "$count" -gt 0 ]; then
            gh api "repos/$REPOSITORY/git/matching-refs/tags/$prefix" -q '.[].ref'
            echo "Found $count tag(s) for $prefix"
          else
            echo "::error::Daily release $prefix is missing!"
            exit 100
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
