name: monitor-sync
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch: {}
jobs:
  monitor-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: |
          cur=$(date -u +'%Y.%m.%d')
          latest=$(gh api "repos/$REPOSITORY/commits?per_page=1" \
            -q '.[0].commit.committer.date')
          latest_commit=$(date -u -d "$latest" +'%Y.%m.%d')
          if [ "$latest_commit" != "$cur" ]; then
            echo "::warning::No repository sync for one or more days (last commit $latest_commit)"
            exit 101
          fi
          echo "Last commit $latest_commit"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
